targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          include_if_null: false
#       freezed:
#         options:
#           union_key: type
#           union_value_case: none